name: Build Extension
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: "true"

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: yarn install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: artifacts
                  path: |
                      extension.vsix
